### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by inverse**
Run tests on CI

### CODE REVIEW

**Comment by mherrmann** [comment]
Looks great. Instead of `pytest`, could we just use `python -m unittest`?

**Comment by inverse** [comment]
@mherrmann Why do you prefer `unittest` over `pytest`? I've mainly only used `pytest` And like the way it can integrate other plugins for generating coverage at the same time etc.

**Comment by mherrmann** [comment]
@inverse I like to have as few additional dependencies as possible. `python -m unittest` does the job just fine.

**Comment by inverse** [comment]
The dependencies are defined in requirements-test and not a hard dependency of the package though. 

I like the additional reporting of deprecated code that it brings. Does unittest provide that?

**Comment by inverse** [comment]
@mherrmann I stand corrected - unittest does also yield deprecated warnings. 

Okays - I'll revert the changes - we can always add it back.

**Comment by mherrmann** [comment]
Thanks!

**Pull request merged**
