### PR TITLE
Added test ignoring all subdirectories

### PR DESCRIPTION
**Pull request by excitoon**
Hi.

I'm happy to tell that you have one more dependent project now, it's https://github.com/excitoon/3 — `tree` replacement. I've found some bugs while testing.

Kind regards,
Vladimir.

### CODE REVIEW

**Comment by excitoon** [comment]
Example: https://github.com/azadkuh/sqlite-amalgamation

**Comment by mherrmann** [comment]
@excitoon the test failed:

```
FAIL: test_ignore_all_subdirectories (tests.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/gitignore_parser/gitignore_parser/tests.py", line 1[16](https://github.com/mherrmann/gitignore_parser/runs/8068808829?check_suite_focus=true#step:4:17), in test_ignore_all_subdirectories
    self.assertFalse(matches('/home/michael/file.txt'))
AssertionError: True is not false
```

Is this a bug or should the `assertFalse` actually be `assertTrue`?

**Comment by excitoon** [comment]
You will have to fix it. Please check how I did it in my module (with some
explanations):
https://github.com/cpburnz/python-path-specification/issues/41#issuecomment-1229529684

**Comment by mherrmann** [comment]
Ok; I've reverted your PR.

**Comment by excitoon** [comment]
Sgtm

**Pull request merged**
