### PR TITLE
Fixing undocumented behavior

### LINKED ISSUE #27: Not working without base_path given
Hi ! Thank you for the implementation, It's great but I had some trouble implementing it in https://github.com/seluj78/potodo

Here's what is happening

`.potodoignore` content
```
venv/
```

```python
from gitignore_parser import parse_gitignore
from pathlib import Path

potodoignore_path = Path("/Users/seluj78/Projects/potodo/.potodoignore")
bad_file = Path("/Users/seluj78/Projects/potodo/venv/bin/python")
matches = parse_gitignore(gitignore_path)
matches(bad_file)  # False
```

But if I change it to this, then it works

```python
from gitignore_parser import parse_gitignore
from pathlib import Path

base_path = Path("/Users/seluj78/Projects/potodo")
bad_file = Path("/Users/seluj78/Projects/potodo/venv/bin/python")
matches = parse_gitignore(".potodoignore", base_dir=base_path)
matches(bad_file)  # True
```

hope this helps !

### PR DESCRIPTION
**Pull request by Seluj78**
What I have done:

- Ran [black](https://pypi.org/project/black/)
- Ran [reorder-python-imports](https://pypi.org/project/reorder-python-imports/)

Closes #27

### CODE REVIEW

**Comment by mherrmann** [comment]
I appreciate the PR but please don't run black. I don't see why we would need to change 90% of lines of code in this project, just to replace some `'`s by `"`s.

I often get PRs where people use or introduce their favorite tools, altering huge parts of the code of my repos with changes that are completely unrelated to the PR. As the maintainer, the "smaller" a PR, that is, the fewer changed lines, the easier it is for me to review it. So I'd kindly ask that you only make those changes here that are absolutely required to implement the feature you want. Changing `'`s to `"`s belongs elsewhere.

**Comment by Seluj78** [comment]
Hi, sorry for the delay.

I understand your point of view, I personally don't agree with it, but it never happened to me either. I reverted back some of the changes that were made by black, mostly the `/'/"`

**Comment by mherrmann** [comment]
I wrote up an [explanation](https://gist.github.com/mherrmann/5ce21814789152c17abd91c0b3eaadca) why I'm asking you to make those changes to the PR. It's a little late in your case, I'm sorry. But I hope you will understand where I'm coming from.

**Comment by Seluj78** [comment]
@mherrmann no worries, I totally understand ! I've reverted the `"` change in tests.py.

I didn't add a test per se, but I did update the tests to use the new format which is https://github.com/mherrmann/gitignore_parser/pull/28/files?file-filters%5B%5D=.py#diff-f455f302936271d755f6892d443786094d2607b505ff180ca817cb9eeabe1e5eR103-R106

`parse_gitignore(base_dir, filename)`, both required

**Comment by mherrmann** [comment]
Thank you. But there are still many more changes in the code than are necessary.

**Comment by Seluj78** [comment]
@mherrmann Alright I cherrypicked the interesting commits and merged them into one. Is it better ?

**Comment by Seluj78** [comment]
There is still some functions that had to be moved to allow for typing.

**Comment by mherrmann** [comment]
Thanks. Now that the diff is smaller, I can begin to understand your work.

Does this PR add anything beyond typing and changing the API to

    parse_gitignore(base_dir, filename)

from

    parse_gitignore(full_path, base_dir=None)

?

**Comment by Seluj78** [comment]
It doesn't no.
Changing the API will allow for clearer documentation and usage of `parse_gitignore`

**Comment by mherrmann** [comment]
I see :( Then I think this entire PR, and all the work that you put in, could have simply been achieved by replacing

    def parse_gitignore(full_path, base_dir=None):
        if base_dir is None:
            base_dir = dirname(full_path)

by

    def parse_gitignore(base_dir, filename):
        full_path = join(base_dir, filename)

If I had seen these three lines as the only part of your commit, then I could have said immediately that there isn't much value here. But because the changes were buried in so many lines, I never had time to look at them all. I am very sorry, but this PR then is just not worth is.

**Comment by mherrmann** [comment]
(And maybe for further clarification: I was hoping your PR would also fix the issue that this library does not mirror the behavior of `git check-ignore venv/bin/python` that we discussed in #27.)

**Pull request closed without merging**
